### ISSUE TITLE
Game speed

### ISSUE THREAD

**Issue by TeodorKolev** [bfirsh/jsnes#172] opened 2018-07-14 20:06 UTC
Is it only me but I see that games speed is super fast and the sound bad? https://jsnes.org/

**Comment by TeodorKolev** [comment] 2018-07-15 11:04
"a little fast"? It is totally unplayable and useless.

**Comment by Tito40** [comment] 2018-07-15 13:54
I play it all the time, it's playable. In the matter of face the speed is not even really noticeable. I'm having little to no problem on my end. I can even show you a video, if you want.

**Comment by TeodorKolev** [comment] 2018-07-16 15:56
I do, please. If it is different I will show video also. Maybe problem is on my side

**Comment by TeodorKolev** [comment] 2018-07-16 16:00
Version 67.0.

**Comment by independentgeorge** [comment] 2018-07-29 12:07
I can confirm it's not just you. Tetris seems super responsive compared to other emulators, but the speed just kills the game.

**Comment by bfirsh** [comment] 2018-07-29 17:03
This is a known problem! Unfortunately we assume that your monitor's refresh rate is 60 fps, the same as the NES's. Your refresh rate is probably faster than that.

I made an attempt at detecting refresh rates and falling back to setInterval, but it didn't work properly so I disabled it: https://github.com/bfirsh/jsnes-web/blob/master/src/FrameTimer.js

More details here: https://github.com/bfirsh/jsnes-web/issues/15

**Comment by independentgeorge** [comment] 2018-07-30 14:37
I don't know about that man, I'm running `requestAnimationFrame` at 58-60 frames.

[Here's a comparison with other emulators.](http://output.jsbin.com/porasoqezi) As you can see the difference is quite drastic.

**Comment by independentgeorge** [comment] 2018-08-01 14:52
@bfirsh Sound also runs faster, in sync with video I'd say.

**Comment by pengan1987** [comment] 2018-10-26 05:48
I have the same problem, if I play a ROM in PAL region originally designed for 50Hz, game will running too fast.

**Comment by kira1928** [comment] 2019-01-07 01:40
I'm not sure if that is the reason, but I noticed that jsnes calculates the additional cpu cycles differently from other reference and other emulator's implementation.

For example:
jsnes adds an additional cpu cycle for AND instruction when the address mode is `ADDR_ABSX`, `ADDR_ABSY` and `ADDR_PREIDXIND`:
https://github.com/bfirsh/jsnes/blob/94f87445bbef3dab0d414b585494c824e887dcd5/src/cpu.js#L308-L320

But other nes references add that additional cycle for AND instruction when the address mode is `ADDR_ABSX`, `ADDR_ABSY` and `ADDR_POSTIDXIND`:
http://obelisk.me.uk/6502/reference.html#AND

BTW, some unofficial instructions in jsnes also have different additional cycle rule than the references I found.

**Comment by bfirsh** [comment] 2019-03-10 21:59
Probably fixed by https://github.com/bfirsh/jsnes-web/pull/195 and https://github.com/bfirsh/jsnes-web/pull/196. Can all here confirm?

**Closed by bfirsh** 2019-03-10 21:59 UTC

**Comment by kira1928** [comment] 2019-03-11 02:13
@bfirsh The latest master branch fixed my game speed problem in android chrome. Thanks!
