### ISSUE TITLE
sound issues

### ISSUE THREAD

**Issue by jancborchardt** [bfirsh/jsnes#15] opened 2012-09-26 17:36 UTC
In Chrome, the sound is choppy (no errors though).

In Firefox (15) when I enable sound, the game effectively pauses, dropping the framerate to 0 and giving this error with dynamicaudio-min.js:
    TypeMismatchError: The type of an object is incompatible with the expected type of the parameter associated to the object

**Comment by davidmarkclements** [comment] 2015-06-09 00:55
* sound is choppy in chrome because jsnes dynamicaudio.js which uses swf fallback in chrome
* sound probably doesn't work in firefox anymore because dynamicaudio.js uses mozWriteAudio which is deprecated

I've been experimenting with the WebAudio API and I have a PoC which gets the sound syncing correctly. 

However I'm struggling with sound quality, I'm pretty certain this is because I'm not converting
from Arrays of numbers between 0-255 (e.g. representing bytes, essentially the equivalent of Uint8Arrays) and Float32Arrays (which is what `buffer.getChannelData` returns).

Also the volume is super high, this can be easily adjusted by applying a ratio to the output, but we shouldn't have to do that. 

Here's my efforts so far (WARNING PUT VOLUME TO MINIMUM BEFORE TESTING): 

https://github.com/davidmarkclements/jsnes/commit/8a4a2244255114aa03d5da2ac0e54ddfb7aa1824#diff-478c5384d0b4a5ca4c1a8e27f9a68c08

The closest sound quality I could get is by passing samples array to Uint16Array, then passing the resulting ArrayBuffer into Float32Array, which is copied (using `set`) into the left and right channels there's probably a better way

It's quite likely that @bfirsh will know exactly how to convert to Float32Array but it seems like he's lost interest :(

**Comment by davidmarkclements** [comment] 2015-06-09 00:58
essentially a duplicate of #7

**Comment by webdevbyjoss** [comment] 2015-12-26 01:41
@davidmarkclements just managed to do the convertion to Float32Array here https://github.com/bfirsh/jsnes/pull/45

**Comment by webdevbyjoss** [comment] 2016-09-09 22:00
moved the WebAudio support to dynamicaudio.js https://github.com/bfirsh/dynamicaudio.js/pull/7

**Comment by bfirsh** [comment] 2016-09-18 09:40
:+1:

**Closed by bfirsh** 2016-09-18 09:40 UTC
