### ISSUE TITLE
this.nes.stop is not a function

### ISSUE THREAD

**Issue by iPG1101** [bfirsh/jsnes#97] opened 2017-12-25 04:04 UTC
Whenever the emulator reads bad data, it loops endlessly because stop is not defined (#24) (#82), and no matter what I do, it won't not do that. Am I loading it wrong? I am using XMLHttpRequest, and reading responseText, but I think this is wrong.

**Comment by bfirsh** [comment] 2017-12-29 09:36
Yes this is a dupe of #24. Thanks for the report!

**Closed by bfirsh** 2017-12-29 09:36 UTC
